[workspace]
members = [
    "alloc",
    "flipperzero",
    "sys",
    "rt",
    "gui",
]
resolver = "2"

[profile.dev]
opt-level = "z"
panic = "abort"

[profile.release]
opt-level = "z"
panic = "abort"
